ALTER TABLE users
RENAME TO movieplanetusers;

ALTER TABLE movieplanetusers
ADD COLUMN email TEXT NOT NULL UNIQUE;

ALTER TABLE movieplanetusers
ADD COLUMN register_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;